#!/bin/sh
set -e

case "$1" in
  remove|upgrade|deconfigure)
    deb-systemd-helper stop llama-scale.service >/dev/null 2>&1 || true
    ;;
esac

if [ "$1" = "remove" ]; then
  deb-systemd-helper disable llama-scale.service >/dev/null 2>&1 || true
  deb-systemd-helper purge llama-scale.service >/dev/null 2>&1 || true
  deb-systemd-helper unmask llama-scale.service >/dev/null 2>&1 || true
fi

exit 0